create database PDataSheet;

create table list (
	Surname varchar(20) not null,
	Firstname varchar(20) not null,
	Middlename varchar(20) not null,
	NameExtension varchar(20),
	DateOfBirth date not null,
	PlaceOfBirth varchar(50) not null,
	Sex varchar(10) not null,
	CivilStatus varchar(15) not null,
	Height float not null,
	Weight float not null,
	BloodType varchar(10) not null,
	GSIS int unique,
	PAGIBIG int unique,
	PHILHEALTH int unique,
	SSS int unique,
	TIN int primary key,
	AgencyEmployment int unique,
	Citizenship varchar(20) not null,
	DualC varchar(20),
	Country varchar(20) not null,
	Rhouse varchar(30) not null,
	Rstreet varchar(30) not null,
	Rsubd varchar(30) not null,
	Rbrgy varchar(30) not null,
	Rcity varchar(30) not null,
	Rprovince varchar(30) not null,
	RZipCode int not null,
	Phouse varchar(30) not null,
	Pstreet varchar(30) not null,
	Psubd varchar(30) not null,
	Pbrgy varchar(30) not null,
	Pcity varchar(30) not null,
	Pprovince varchar(30) not null,
	PZipCode int not null,
	Telephone varchar(15) not null,
	Mobile varchar(15) not null,
	Email varchar(30) not null,
	SSurname varchar(20) not null,
	SFirstname varchar(20) not null,
	SMiddlename varchar(20) not null,
	SNameExtension varchar(20),
	SOccupation varchar(20) not null,
	SEmployer varchar(20) not null,
	SBAddress varchar(50) not null,
	STelephone varchar(15) not null,
	Childname1 varchar(50),
	Childname2 varchar(50),
	Childname3 varchar(50),
	Childname4 varchar(50),
	Childname5 varchar(50),
	Childname6 varchar(50),
	Childname7 varchar(50),
	Childname8 varchar(50),
	Childname9 varchar(50),
	Childname10 varchar(50),
	Childname11 varchar(50),
	Childname12 varchar(50),
	Childbirth1 varchar(50),
	Childbirth2 varchar(50),
	Childbirth3 varchar(50),
	Childbirth4 varchar(50),
	Childbirth5 varchar(50),
	Childbirth6 varchar(50),
	Childbirth7 varchar(50),
	Childbirth8 varchar(50),
	Childbirth9 varchar(50),
	Childbirth10 varchar(50),
	Childbirth11 varchar(50),
	Childbirth12 varchar(50),
	FSurname varchar(20) not null,
	FFirstname varchar(20) not null,
	FMiddlename varchar(20) not null,
	FNameExtension varchar(20),
	MMaidenname varchar(20) not null,
	MSurname varchar(20) not null,
	MFirstname varchar(20) not null,
	MMiddlename varchar(20) not null,
	ENameOfSchool varchar(50),
	EBasic varchar(50),
	EPeriodFrom int,
	EPeriodTo int,
	EHighestLevel varchar(20),
	EYearGraduated int,
	EScholarshipHonor varchar(20),
	HSNameOfSchool varchar(50),
	HSBasic varchar(50),
	HSPeriodFrom int,
	HSPeriodTo int,
	HSHighestLevel varchar(20),
	HSYearGraduated int,
	HSScholarshipHonor varchar(20),
	VNameOfSchool varchar(50),
	VBasic varchar(50),
	VPeriodFrom int,
	VPeriodTo int,
	VHighestLevel varchar(20),
	VYearGraduated int,
	VScholarshipHonor varchar(20),
	CNameOfSchool varchar(50),
	CBasic varchar(50),
	CPeriodFrom int,
	CPeriodTo int,
	CHighestLevel varchar(20),
	CYearGraduated int,
	CScholarshipHonor varchar(20),
	GSNameOfSchool varchar(50),
	GSBasic varchar(50),
	GSPeriodFrom int,
	GSPeriodTo int,
	GSHighestLevel varchar(20),
	GSYearGraduated int,
	GSScholarshipHonor varchar(20)
	
);

create table education (
	TIN int primary key,
	ENameOfSchool varchar(50),
	EBasic varchar(50),
	EPeriodFrom int,
	EPeriodTo int,
	EHighestLevel varchar(20),
	EYearGraduated int,
	EScholarshipHonor varchar(20),
	HSNameOfSchool varchar(50),
	HSBasic varchar(50),
	HSPeriodFrom int,
	HSPeriodTo int,
	HSHighestLevel varchar(20),
	HSYearGraduated int,
	HSScholarshipHonor varchar(20),
	VNameOfSchool varchar(50),
	VBasic varchar(50),
	VPeriodFrom int,
	VPeriodTo int,
	VHighestLevel varchar(20),
	VYearGraduated int,
	VScholarshipHonor varchar(20),
	CNameOfSchool varchar(50),
	CBasic varchar(50),
	CPeriodFrom int,
	CPeriodTo int,
	CHighestLevel varchar(20),
	CYearGraduated int,
	CScholarshipHonor varchar(20),
	GSNameOfSchool varchar(50),
	GSBasic varchar(50),
	GSPeriodFrom int,
	GSPeriodTo int,
	GSHighestLevel varchar(20),
	GSYearGraduated int,
	GSScholarshipHonor varchar(20)
	
);

create table scholarship (
	TIN int primary key,
	GSScholarshipHonor varchar(20)
);